@url_dev = http://localhost:3052/v1/api/comment
@key_seach = IPhone
### unpublic product 
POST {{url_dev}}
Content-Type: application/json
x-client-id: 660e63072c74b1d4e3484727
x-api-key: 53a354b9c0a0bc5c2f964cc21a1d45cefe7830c3453210f673ddd1e8c89db61eeee9e19fa60e25d74e29b45c83bdaeaad7c2079cf2bccf5e0958769cbd7db8b4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjBlNjMwNzJjNzRiMWQ0ZTM0ODQ3MjciLCJlbWFpbCI6InRoYXR2MTIxY2VkMmNjQGdtYWlsLmNvbSIsImlhdCI6MTcxNjU3NzQxMSwiZXhwIjoxNzE3MTgyMjExfQ.WFrwGMgQZt2a1orDLlbRooG1OTH3fGAfe31lgo6NR-dKWZomXcHoSbcqcFvzEFGtnbT_VNUSK-P4n_Kse2fVLLZM42uuhRkiYcDnNSeSSkt9qHDrfTA10XqQd1qg8PS1g0EYC-hDx6I69oWdgSRWHCBpiRQLWweAxuGbC__cXrL9eGBwCWaCh6BK803ZgBxNxhHj68fo5-XuGrDhK9SqEcIRyf5LaKZn8EYFbpYDX9rYe7T6Gaen92rhVnJCOJu4c1NM2C6Q8S2YAGmSXyfVPrlVe7uj5bMg3gZsZcqvM4z9vqoe-qEcgQlrHZRVB5ZbuoZUcaPcbQEiXo0vXxk2eA

{
    "productId": "6628ec97a6ee5adda06cdfbd",
    "userId": 1,
    "content": "Comment 2",
    "parentId": "6650e6249b241fda5c92d425"
}