@url_dev = http://localhost:3052/v1/api/
### sign up
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 53a354b9c0a0bc5c2f964cc21a1d45cefe7830c3453210f673ddd1e8c89db61eeee9e19fa60e25d74e29b45c83bdaeaad7c2079cf2bccf5e0958769cbd7db8b4

{
    "name": "shopes2331232221",
    "email": "thatv121ced2cc@gmail.com",
    "password": "1212"
}

### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 53a354b9c0a0bc5c2f964cc21a1d45cefe7830c3453210f673ddd1e8c89db61eeee9e19fa60e25d74e29b45c83bdaeaad7c2079cf2bccf5e0958769cbd7db8b4

{
    "email": "thatv121ced2cc@gmail.com",
    "password": "1212"
}



### logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-client-id: 660e63072c74b1d4e3484727
x-api-key: 53a354b9c0a0bc5c2f964cc21a1d45cefe7830c3453210f673ddd1e8c89db61eeee9e19fa60e25d74e29b45c83bdaeaad7c2079cf2bccf5e0958769cbd7db8b4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjBlNjMwNzJjNzRiMWQ0ZTM0ODQ3MjciLCJlbWFpbCI6InRoYXR2MTIxY2VkMmNjQGdtYWlsLmNvbSIsImlhdCI6MTcxMjQxNzM3MSwiZXhwIjoxNzEyNTkwMTcxfQ.Pg9V9NN6PcVTTfu4pKkm0xvBsxG0Zlpg87P3GXMpgCQWq8d3UJHRppHesrrk2Ye9ButaSolVpzNn8fQ1hYSTjIFYqCrV1hrQtpGwpCazR9lghV4lVxIPpRk5avK6W57i12RSzON0t_ZKq4lE1nSXLN0lS5GVKeXq9Xx8JzSukyAWq8lYWP_rrNz5W7sTmMvst7VscIQ70JkiWWHXBkQkogLAK-dsWeNJ2wFpWq8Z-d8Ptg9AV6Fvw7J5YBPqZmn6IENHR7USQX_0B2KhoyMvVrt0uFae2eRqZjLY8I3iEB1_zStYCUV7xIOQEnkS15rQ5oMseBwGjaM6oUEFaPBY0w


### logout
POST {{url_dev}}/shop/handleRefreshToken
Content-Type: application/json
x-client-id: 660e63072c74b1d4e3484727
x-api-key: 53a354b9c0a0bc5c2f964cc21a1d45cefe7830c3453210f673ddd1e8c89db61eeee9e19fa60e25d74e29b45c83bdaeaad7c2079cf2bccf5e0958769cbd7db8b4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjBlNjMwNzJjNzRiMWQ0ZTM0ODQ3MjciLCJlbWFpbCI6InRoYXR2MTIxY2VkMmNjQGdtYWlsLmNvbSIsImlhdCI6MTcxMjY1Mjg2NywiZXhwIjoxNzEyODI1NjY3fQ.Y21ESD1sKLOu-A3QD6sbjMDU-2FBABMJDBlu77ETiusfi8YpA1R2cx_2l-c7byBhw00w6Un8bD3r-LPMBFtz0LvZccuqZrXe-nAgy9IVmE5gWqnrejOFRaftV2HU1iuFiQlLmu4bFFcPSXaAHI53zD_NSQ9E_HztojA-eZZZAGJh7EbTPQqPplheFJ0UOqUxFa2Mp0Rj5rJ7kPzhzU-ct1REMkO8DV7Uh3y_76tue-5ICZbYgVcptxXMi2OJJxsV359_VaQ589NJVAB5Ko1po_53ya07fxDZrpVRuglHxafZLGxXPNMzK_ALZhIZ2lhGkAF8BBhPJhB43Fe8-4dwSQ

{
     "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjBlNjMwNzJjNzRiMWQ0ZTM0ODQ3MjciLCJlbWFpbCI6InRoYXR2MTIxY2VkMmNjQGdtYWlsLmNvbSIsImlhdCI6MTcxMjY1Mjg2NywiZXhwIjoxNzEzMjU3NjY3fQ.x6-n1RBYLM0a3LuKzU5npJtOkTErPX6HABfY0I-YHilaxqwBV15ZxnIVEMPLPyfd62EnfJBuiRtBky6UoT3jHd7VFQJ73yUPvbdLUPKlMlNnFt8SQveu9BotJdUQoiWxr3azjiI3hncKIN6fFAB1NHBgbh-tHFHl6n7HkxI1rckIzg2EH7B5jSUPeDTdc64bmMNSG8EmVfXfE3oFp_OwpJCKRF7gLZs0rJzdGa52i5egvDTJgOnhRBkEjYZdBcw_ZJe9wRF6SMSyXsRRafRZFlWwrJe947HGcZRXi85Xgd4auxAGeuvsko_WmLnmrmKV4IqsuWiaY_FLq7jvOXLohQ"
}